In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
close_1_data=pd.read_csv('processedData/eur_usd_1min_1_close.csv')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:

x=close_1_data.iloc[:,1:-1].values
y=close_1_data.iloc[:,5].values

x, y = np.array(x), np.array(y)
x = np.reshape(x, (x.shape[0], x.shape[1], 1))
print(x)
print(y)

[[[0.9181 ]
  [0.9181 ]
  [0.9181 ]
  [0.9181 ]]

 [[0.9152 ]
  [0.9152 ]
  [0.9152 ]
  [0.9152 ]]

 [[0.9042 ]
  [0.9042 ]
  [0.9042 ]
  [0.9042 ]]

 ...

 [[1.44199]
  [1.44209]
  [1.44199]
  [1.44209]]

 [[1.4421 ]
  [1.44229]
  [1.44209]
  [1.44221]]

 [[1.44229]
  [1.44239]
  [1.44219]
  [1.44219]]]
[ 1. -1. -1. ...  1.  1. -1.]


In [5]:
x_train_val,x_test, y_train_val, y_test=train_test_split(x,y,test_size=0.30,shuffle=False)
x_train,x_val, y_train, y_val=train_test_split(x_train_val,y_train_val,test_size=0.25)

In [6]:
print(len(x_train),len(x_test), len(x_val))

550500 314572 183501


In [ ]:

from keras.layers import LSTM
from keras.layers import Dropout

Using TensorFlow backend.


In [ ]:
regressor = Sequential()
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (x.shape[1], 1)))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))
regressor.add(Dense(units = 1))